name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    env:
      VCPKG_BINARY_SOURCES: 'clear;nuget,GitHub,readwrite'
      VCPKG_ROOT: './vcpkg'
      BUILD_TYPE: Release
      
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: 'tartanllama/vcpkg'
          path: 'vcpkg'
    
      - uses: seanmiddleditch/gha-setup-ninja@master
      - uses: ilammy/msvc-dev-cmd@v1
      
      - name: 'Bootstrap vcpkg'
        run: ./vcpkg/bootstrap-vcpkg.bat
        
      - name: 'Setup NuGet Credentials'
        shell: 'bash'
        run: >
          `./vcpkg/vcpkg fetch nuget | tail -n 1`
          sources add
          -source "https://nuget.pkg.github.com/tartanllama/index.json"
          -storepasswordincleartext
          -name "GitHub"
          -username "tartanllama"
          -password "${{ secrets.GITHUB_TOKEN }}"
          
      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build --preset=windows-default

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
        
